name: Build App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Archive
      run: |
        mkdir package
        cp index.html package/
        if [ -f "14783.png" ]; then cp 14783.png package/; fi
        cd package && zip -r ../app.zip *
    - uses: actions/upload-artifact@v3
      with:
        name: YouxEnglish-App
        path: app.zip
